version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    # таблицы и их содержимое
    - ./db_data/postgres:/var/lib/postgresql/data
    - ./db_data/run/postgres.sock:/var/run/postgres/postgres.sock
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./db_data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge
  